In [2]:
import numpy as np


In [9]:
100//101


0

In [21]:

a.shape
A=np.mat(a)
a1=[[1,2],[3,2],[5,100]]
#a1=np.mat(a1)
a1

[[1, 2], [3, 2], [5, 100]]

In [22]:

np.argmax(a1)


5

In [25]:

a = np.array([
              [
                  [1, 5, 5, 2],
                  [9, -6, 2, 8],
                  [-3, 7, -9, 1]
              ],
 
              [
                  [-1, 7, -5, 2],
                  [9, 6, 2, 8],
                  [3, 7, 9, 1]
              ],
            [
                  [21, 6, -5, 2],
                  [9, 36, 2, 8],
                  [3, 7, 79, 1]
              ]
            ])
np.argmax(a,axis=2)

array([[1, 0, 1],
       [1, 0, 2],
       [0, 1, 2]])

In [51]:
np.std(a,axis=1)**2

array([0.66666667, 2.66666667])

In [50]:
np.var(a,axis=1)

array([0.66666667, 2.66666667])

In [5]:
a.reshape((3,：))  #不可以

SyntaxError: invalid character in identifier (<ipython-input-5-9952b409a3c9>, line 1)

In [6]:
a.flatten()[1]=0

In [7]:
a

array([[[-0.88380143, -0.63543999, -0.3294554 ,  0.37234324,
          2.42867853,  0.50766805],
        [-0.60209207,  1.34245255,  0.70489179, -0.94150428,
         -0.18336821, -1.02541371],
        [ 0.17878614, -0.09169017,  0.80536996, -1.08315221,
         -1.42336801, -1.88445819],
        [ 0.41676362,  0.20699237, -0.71175471, -1.14954609,
          0.24565199,  0.60396283],
        [ 1.10488601,  0.67790072, -1.63227528, -0.27273573,
          0.0746096 ,  2.15889384]],

       [[-1.19783182, -0.87438709, -1.53746681,  0.50356362,
          0.04304569, -0.45223153],
        [ 0.53496745,  1.68954463,  0.96093313,  0.05833252,
          0.83904344,  1.21535506],
        [-1.23509883,  0.49814477, -1.38276762,  1.51795327,
          0.40281704, -0.0838327 ],
        [ 1.22032305, -0.40683856, -1.05175898,  1.29631888,
         -0.1417491 ,  0.32709386],
        [ 0.25074096, -0.67708024, -0.88586293,  1.66218384,
         -0.86828742,  0.38225895]],

       [[ 0.43638748, -0.6

In [8]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape) #相乘

In [9]:
input_size

240

In [10]:
*(8,9,10)

SyntaxError: can't use starred expression here (<ipython-input-10-4085492fd30e>, line 1)

In [11]:
b=np.random.randn(3,5)

In [12]:
b.T[0][1]=0

In [13]:
b

array([[ 0.17770554, -0.22703777,  0.24072195,  1.084035  , -0.39962293],
       [ 0.        , -0.97395904, -0.2011669 ,  1.68546315, -1.58206714],
       [ 0.08596292,  0.31273706,  0.66302879,  0.21289122, -0.60571452]])

In [14]:
a.T

array([[[-0.88380143, -1.19783182,  0.43638748],
        [-0.60209207,  0.53496745,  0.44665972],
        [ 0.17878614, -1.23509883, -1.48356981],
        [ 0.41676362,  1.22032305,  1.15167905],
        [ 1.10488601,  0.25074096,  0.38763923]],

       [[-0.63543999, -0.87438709, -0.64997391],
        [ 1.34245255,  1.68954463, -0.43007318],
        [-0.09169017,  0.49814477, -1.22654294],
        [ 0.20699237, -0.40683856,  0.83221946],
        [ 0.67790072, -0.67708024,  1.20081698]],

       [[-0.3294554 , -1.53746681, -0.29836407],
        [ 0.70489179,  0.96093313,  0.60098098],
        [ 0.80536996, -1.38276762, -0.4006397 ],
        [-0.71175471, -1.05175898,  1.87922957],
        [-1.63227528, -0.88586293, -2.00684338]],

       [[ 0.37234324,  0.50356362,  1.5173949 ],
        [-0.94150428,  0.05833252, -1.43597884],
        [-1.08315221,  1.51795327,  0.04624388],
        [-1.14954609,  1.29631888, -0.65590736],
        [-0.27273573,  1.66218384, -0.51833118]],

       [[ 2.

In [15]:
a.T.dot(b).shape

(6, 5, 5)

In [16]:
np.random.randn(3,5,6,7).T.shape

(7, 6, 5, 3)

In [17]:
np.max(a)

2.4286785338777483

In [18]:
np.maximum(1,a)

array([[[1.        , 1.        , 1.        , 1.        , 2.42867853,
         1.        ],
        [1.        , 1.34245255, 1.        , 1.        , 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        ],
        [1.10488601, 1.        , 1.        , 1.        , 1.        ,
         2.15889384]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        ],
        [1.        , 1.68954463, 1.        , 1.        , 1.        ,
         1.21535506],
        [1.        , 1.        , 1.        , 1.51795327, 1.        ,
         1.        ],
        [1.22032305, 1.        , 1.        , 1.29631888, 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , 1.66218384, 1.        ,
         1.        ]],

       [[1.        , 1.        , 1.        , 1.5173949 , 1.        ,
         1.      

In [19]:
b

array([[ 0.17770554, -0.22703777,  0.24072195,  1.084035  , -0.39962293],
       [ 0.        , -0.97395904, -0.2011669 ,  1.68546315, -1.58206714],
       [ 0.08596292,  0.31273706,  0.66302879,  0.21289122, -0.60571452]])

In [20]:
b-np.arange(3)[:,np.newaxis]

array([[ 0.17770554, -0.22703777,  0.24072195,  1.084035  , -0.39962293],
       [-1.        , -1.97395904, -1.2011669 ,  0.68546315, -2.58206714],
       [-1.91403708, -1.68726294, -1.33697121, -1.78710878, -2.60571452]])

In [21]:
b-np.arange(3)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [22]:
x=np.array([[1001, 1002], [3, 4]])
np.max(x, axis=1, keepdims=True)


array([[1002],
       [   4]])

In [23]:
i=9
"%shfks" % (i+1)

'10hfks'

In [24]:
bb = [1,3,5]
v = [ 3,4]
v.append(1)
v

[3, 4, 1]

In [25]:
bb.extend([10])

In [26]:
nn=np.array([1,2,3])

In [27]:
nn.dtype

dtype('int64')

In [28]:
kk = nn.astype(np.float)

In [29]:
kk.dtype

dtype('float64')

In [30]:
nn**2

array([1, 4, 9])

In [31]:
nn.dtype

dtype('int64')

In [32]:
0=
 5

SyntaxError: invalid syntax (<ipython-input-32-2657586cf203>, line 1)

In [33]:
range(2,1)

range(2, 1)

In [34]:
for i in range(2,3):
    print(i)

2


In [35]:
i

2