In [1]:
for i in range (9):
    pass
print(i)

8


In [2]:
for i in range (7):
    print(i)

0
1
2
3
4
5
6


In [3]:
print(i)

6


In [4]:
import numpy as np


In [5]:
a=np.array([[1, 2, 3 ],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b=np.ones(3)
b

array([1., 1., 1.])

In [7]:
a-b

array([[0., 1., 2.],
       [3., 4., 5.]])

In [8]:
np.sum(a,axis=1)

array([ 6, 15])

In [9]:
c=np.ones(2)
print(c.shape)
c=c.T
c.shape
c[1]=2

(2,)


In [10]:
np.repeat(c,a.shape)

array([1., 1., 2., 2., 2.])

In [11]:
bb=np.arange(10)
bb.shape

(10,)

In [12]:
cv=np.array_split(bb,3)

In [13]:
cv


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [14]:
cv[1]

array([4, 5, 6])

In [15]:
oo=np.ones((100,80))

In [16]:
oo

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [17]:
splitoo=np.array_split(oo
                       ,5,
                       axis=0)  ####括号里参数间是可以换行的

In [18]:
np.shape(splitoo[0])

(20, 80)

In [19]:
#nb=np.concatenate(splitoo[:2]+splitoo[3:])
nb=np.concatenate(splitoo[:1+3:])

In [20]:
nb.shape

(80, 80)

In [21]:
jb=list([1,2,3,4])

In [22]:
jb

[1, 2, 3, 4]

In [23]:
np.array(jb)

array([1, 2, 3, 4])

In [24]:
mk=np.ones((5,3))

In [25]:
np.mean(mk,axis=1)

array([1., 1., 1., 1., 1.])

In [26]:
np.sum(mk)

15.0

In [27]:
mk[1]

array([1., 1., 1.])

In [28]:
mk[1,2]

1.0

In [29]:
mk[1]

array([1., 1., 1.])

In [30]:
mk[:,1]

array([1., 1., 1., 1., 1.])

In [31]:
mk[:]   

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
y=np.ones(2,dtype=int)
margin=np.array([[10,1,3],[4,10,6]])
margin
jj=margin
jj[1][1]=2
print(np.sum(-np.log(margin)))
margin,jj

-7.272398392570047


(array([[10,  1,  3],
        [ 4,  2,  6]]), array([[10,  1,  3],
        [ 4,  2,  6]]))

In [33]:
margin.sum(axis=1)

array([14, 12])

In [34]:
np.argmax(margin,axis=1)

array([0, 2])

In [35]:
[1,2]+[2,4]

[1, 2, 2, 4]

In [36]:
np.exp(margin)

array([[2.20264658e+04, 2.71828183e+00, 2.00855369e+01],
       [5.45981500e+01, 7.38905610e+00, 4.03428793e+02]])

In [37]:
np.log10(0.353)

-0.4522252946121775

In [38]:
margin

array([[10,  1,  3],
       [ 4,  2,  6]])

In [40]:
np.maximum(0,margin)

array([[10,  1,  3],
       [ 4,  2,  6]])

In [44]:
np.ones((margin>5)*margin)

TypeError: only integer scalar arrays can be converted to a scalar index

In [46]:
np.random.choice(margin,1)

ValueError: a must be 1-dimensional

In [49]:
np.argmax(margin,axis=0)

array([0, 1, 1])